def get_milestone_for_week(week: int) -> dict | None:
    fetal_milestones = {
        1: {"week": 1, "size": "Poppy seed", "weight": 0.02, "length": 0.01, "developments": ["Fertilization occurs", "Cell division begins"], "tips": ["Take folic acid", "Stay hydrated"]},
        2: {"week": 2, "size": "Poppy seed", "weight": 0.02, "length": 0.02, "developments": ["Neural tube forming", "Amniotic sac develops"], "tips": ["Eat nutrient-dense foods"]},
        3: {"week": 3, "size": "Lentil", "weight": 0.03, "length": 0.03, "developments": ["Heart begins to form", "Neural tube closes"], "tips": ["Prenatal checkup"]},
        4: {"week": 4, "size": "Sesame seed", "weight": 0.05, "length": 0.15, "developments": ["Heart begins to beat", "Limb buds appear"], "tips": ["Check medication safety"]},
        5: {"week": 5, "size": "Apple seed", "weight": 0.1, "length": 0.2, "developments": ["Face features forming", "Circulation starts"], "tips": ["Rest when tired"]},
        6: {"week": 6, "size": "Lentil", "weight": 0.2, "length": 0.4, "developments": ["Brain develops rapidly", "Heart pumps blood"], "tips": ["Ginger tea for nausea"]},
        7: {"week": 7, "size": "Blueberry", "weight": 0.5, "length": 0.7, "developments": ["Fingers begin to form", "Upper lip forms"], "tips": ["Gentle walks"]},
        8: {"week": 8, "size": "Raisin", "weight": 1.0, "length": 1.5, "developments": ["All major organs formed", "External ears visible"], "tips": ["Choose maternity clinic"]},
        9: {"week": 9, "size": "Green olive", "weight": 2.0, "length": 2.2, "developments": ["Muscles develop", "Baby begins moving"], "tips": ["Increase calcium"]},
        10: {"week": 10, "size": "Strawberry", "weight": 5.0, "length": 3.8, "developments": ["Organs functioning", "Swallowing begins"], "tips": ["Avoid raw foods"]},
        11: {"week": 11, "size": "Lime", "weight": 7.0, "length": 4.1, "developments": ["Baby starts kicking", "Hair follicles forming"], "tips": ["First trimester screening"]},
        12: {"week": 12, "size": "Plum", "weight": 14.0, "length": 5.4, "developments": ["Reflexes develop", "Kidneys start producing urine"], "tips": ["Announce pregnancy?"]},
        13: {"week": 13, "size": "Lemon", "weight": 23.0, "length": 7.4, "developments": ["Kidneys working", "Fingerprints forming"], "tips": ["Start side sleeping"]},
        14: {"week": 14, "size": "Nectarine", "weight": 43.0, "length": 8.7, "developments": ["Baby can squint and frown", "Sucking thumb"], "tips": ["Posture check"]},
        15: {"week": 15, "size": "Apple", "weight": 70.0, "length": 10.1, "developments": ["Skeleton hardening", "Hearing develops"], "tips": ["Talk to baby"]},
        16: {"week": 16, "size": "Avocado", "weight": 100.0, "length": 11.6, "developments": ["Lungs begin to breathe amniotic fluid", "Nervous system matures"], "tips": ["Moisturize skin"]},
        17: {"week": 17, "size": "Pear", "weight": 140.0, "length": 13.0, "developments": ["Fat stores developing", "Sweat glands forming"], "tips": ["Check for swelling"]},
        18: {"week": 18, "size": "Sweet potato", "weight": 190.0, "length": 14.2, "developments": ["Genitals visible", "Baby is very active"], "tips": ["Mid-pregnancy ultrasound"]},
        19: {"week": 19, "size": "Mango", "weight": 240.0, "length": 15.3, "developments": ["Vernix coating skin", "Sensory development"], "tips": ["Stay hydrated"]},
        20: {"week": 20, "size": "Banana", "weight": 300.0, "length": 25.6, "developments": ["Halfway point", "Sleep cycles forming"], "tips": ["Anatomy scan"]},
        21: {"week": 21, "size": "Pomegranate", "weight": 360.0, "length": 26.7, "developments": ["Eyelids still fused", "Bone marrow works"], "tips": ["Iron-rich foods"]},
        22: {"week": 22, "size": "Coconut", "weight": 430.0, "length": 27.8, "developments": ["Sense of touch develops", "Lips and eyebrows form"], "tips": ["Stretch marks care"]},
        23: {"week": 23, "size": "Grapefruit", "weight": 500.0, "length": 28.9, "developments": ["Inner ear developed", "Blood vessels in lungs"], "tips": ["Watch for Braxton Hicks"]},
        24: {"week": 24, "size": "Peach", "weight": 600.0, "length": 30.0, "developments": ["Lungs developing", "Taste buds forming"], "tips": ["Glucose screening"]},
        25: {"week": 25, "size": "Cauliflower", "weight": 660.0, "length": 34.6, "developments": ["Baby starts responding to sound", "Nostrils open"], "tips": ["Rest frequently"]},
        26: {"week": 26, "size": "Kale", "weight": 760.0, "length": 35.6, "developments": ["Eyes start to open", "Brain activity increases"], "tips": ["Belly support belt?"]},
        27: {"week": 27, "size": "Lettuce", "weight": 875.0, "length": 36.6, "developments": ["Lungs continue to mature", "Fat accumulation"], "tips": ["Third trimester begins"]},
        28: {"week": 28, "size": "Eggplant", "weight": 1000.0, "length": 37.6, "developments": ["Eyes can open", "Dreaming begins"], "tips": ["Kick counts"]},
        29: {"week": 29, "size": "Acorn squash", "weight": 1150.0, "length": 38.6, "developments": ["Brain controls breathing", "Body temperature regulation"], "tips": ["Finalize birth plan"]},
        30: {"week": 30, "size": "Cucumber", "weight": 1300.0, "length": 39.9, "developments": ["Early hair shedding", "Eyes wide open"], "tips": ["Hospital tour"]},
        31: {"week": 31, "size": "Pineapple", "weight": 1500.0, "length": 41.1, "developments": ["Rapid brain growth", "Lungs maturing"], "tips": ["Wash baby clothes"]},
        32: {"week": 32, "size": "Large mango", "weight": 1700.0, "length": 42.4, "developments": ["Practicing breathing", "Toenails formed"], "tips": ["Discuss labor signs"]},
        33: {"week": 33, "size": "Durian", "weight": 1900.0, "length": 43.7, "developments": ["Immune system boost", "Baby moving lower"], "tips": ["Pelvic exercises"]},
        34: {"week": 34, "size": "Cantaloupe", "weight": 2100.0, "length": 45.0, "developments": ["Central nervous system", "Vernix thickening"], "tips": ["Finalize nursery"]},
        35: {"week": 35, "size": "Honeydew", "weight": 2400.0, "length": 46.2, "developments": ["Kidneys fully developed", "Lever processing waste"], "tips": ["Pack hospital bag"]},
        36: {"week": 36, "size": "Papaya", "weight": 2600.0, "length": 47.4, "developments": ["Baby drops into pelvis", "Fat gain continues"], "tips": ["Install car seat"]},
        37: {"week": 37, "size": "Winter melon", "weight": 2850.0, "length": 48.6, "developments": ["Early term baby", "Practicing sucking"], "tips": ["Monitor contractions"]},
        38: {"week": 38, "size": "Pumpkin", "weight": 3100.0, "length": 49.8, "developments": ["Organs ready", "Grasp reflex strong"], "tips": ["Sleep as much as possible"]},
        39: {"week": 39, "size": "Watermelon", "weight": 3300.0, "length": 50.7, "developments": ["Full term", "Skin becoming smooth"], "tips": ["Stay calm and ready"]},
        40: {"week": 40, "size": "Watermelon", "weight": 3500.0, "length": 52.0, "developments": ["Ready for birth", "Placenta providing immunity"], "tips": ["Monitor for labor"]},
    }
    return fetal_milestones.get(week)