def get_milestone_for_week(week: int) -> dict | None:
    fetal_milestones = {
        1: {
            "week": 1,
            "baby_size": "Poppy seed",
            "baby_weight": "0.02g",
            "baby_length": "0.1mm",
            "development": "Fertilization occurs, cell division begins",
            "symptoms": "Missed period, spotting (implantation bleeding)",
        },
        2: {
            "week": 2,
            "baby_size": "Poppy seed",
            "baby_weight": "0.02g",
            "baby_length": "0.2mm",
            "development": "Neural tube begins forming, amniotic sac develops",
            "symptoms": "Implantation bleeding may occur",
        },
        3: {
            "week": 3,
            "baby_size": "Lentil",
            "baby_weight": "0.03g",
            "baby_length": "0.3mm",
            "development": "Neural tube closes, heart begins to form",
            "symptoms": "Early pregnancy symptoms begin",
        },
        4: {
            "week": 4,
            "baby_size": "Sesame seed",
            "baby_weight": "0.05g",
            "baby_length": "1.5mm",
            "development": "Heart begins to beat, limb buds appear",
            "symptoms": "Missed period, positive pregnancy test",
        },
        5: {
            "week": 5,
            "baby_size": "Apple seed",
            "baby_weight": "0.1g",
            "baby_length": "2mm",
            "development": "Arm and leg buds grow longer",
            "symptoms": "Tender breasts, fatigue",
        },
        6: {
            "week": 6,
            "baby_size": "Lentil",
            "baby_weight": "0.2g",
            "baby_length": "4mm",
            "development": "Brain develops rapidly, heart pumps blood",
            "symptoms": "Nausea may begin, frequent urination",
        },
        7: {
            "week": 7,
            "baby_size": "Blueberry",
            "baby_weight": "0.5g",
            "baby_length": "7mm",
            "development": "Upper lip and nose form, fingers begin to form",
            "symptoms": "Morning sickness peaks, mood swings",
        },
        8: {
            "week": 8,
            "baby_size": "Raisin",
            "baby_weight": "1g",
            "baby_length": "15mm",
            "development": "All major organs formed, external ears visible",
            "symptoms": "Fatigue, breast tenderness",
        },
        9: {
            "week": 9,
            "baby_size": "Green olive",
            "baby_weight": "2g",
            "baby_length": "22mm",
            "development": "Fingers and toes webbed, muscles develop",
            "symptoms": "Nausea, food aversions",
        },
        10: {
            "week": 10,
            "baby_size": "Strawberry",
            "baby_weight": "5g",
            "baby_length": "38mm",
            "development": "Organs functioning, swallowing begins",
            "symptoms": "Less nausea for some, energy returning",
        },
        13: {
            "week": 13,
            "baby_size": "Lemon",
            "baby_weight": "15g",
            "baby_length": "74mm",
            "development": "Kidneys working, fingerprints forming",
            "symptoms": "Second trimester energy boost",
        },
        16: {
            "week": 16,
            "baby_size": "Avocado",
            "baby_weight": "70g",
            "baby_length": "115mm",
            "development": "Sucking thumb, bone marrow producing blood cells",
            "symptoms": "Baby bump visible, backaches",
        },
        20: {
            "week": 20,
            "baby_size": "Banana",
            "baby_weight": "280g",
            "baby_length": "250mm",
            "development": "Halfway there! Boy or girl visible on ultrasound",
            "symptoms": "Feeling baby movements (quickening)",
        },
        24: {
            "week": 24,
            "baby_size": "Peach",
            "baby_weight": "600g",
            "baby_length": "300mm",
            "development": "Lungs developing, taste buds forming",
            "symptoms": "Growing belly, back pain",
        },
        28: {
            "week": 28,
            "baby_size": "Eggplant",
            "baby_weight": "1000g",
            "baby_length": "365mm",
            "development": "Eyes can open, brain developing rapidly",
            "symptoms": "Third trimester begins, frequent urination",
        },
        32: {
            "week": 32,
            "baby_size": "Large mango",
            "baby_weight": "1700g",
            "baby_length": "420mm",
            "development": "Lungs maturing, brain developing",
            "symptoms": "Braxton Hicks contractions, shortness of breath",
        },
        36: {
            "week": 36,
            "baby_size": "Papaya",
            "baby_weight": "2600g",
            "baby_length": "470mm",
            "development": "Mostly developed, lungs ready for birth",
            "symptoms": "Nesting instinct, pelvic pressure",
        },
        40: {
            "week": 40,
            "baby_size": "Watermelon",
            "baby_weight": "3400g",
            "baby_length": "520mm",
            "development": "Full term baby ready to meet you",
            "symptoms": "Ready for labor, excitement!",
        },
    }
    return fetal_milestones.get(week)